name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: |
          curl -Ls https://github.com/koalaman/shellcheck/releases/download/v0.10.0/shellcheck-v0.10.0.linux.x86_64.tar.xz | \
          tar xJ --strip-components=1 shellcheck-v0.10.0/shellcheck

      - name: Run ShellCheck
        run: |
          ./shellcheck --color=always srcenv srcenv.tests srcenv.version && \
          printf "\e[32m✔\e[0m ShellCheck\n"

      - name: Run srcenv tests
        run: ./srcenv.tests