name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ShellCheck
        shell: bash
        run: |
          curl -Ls https://github.com/koalaman/shellcheck/releases/download/v0.10.0/shellcheck-v0.10.0.linux.x86_64.tar.xz | \
          tar xJ --strip-components=1 shellcheck-v0.10.0/shellcheck
      - name: Run ShellCheck
        run: ./shellcheck --color=always srcenv srcenv.tests
      - name: Run srcenv tests
        run: ./srcenv.tests